### ISSUE TITLE
Datei Update Fehler

### ISSUE THREAD

**Issue by PeperoniRMA** [RMArchiv/rmarchiv#255]
Betrifft eventuell nur Dateien älterer Spieleinträge oder nur das Spiel "Sieben".
Aber das weiß ich selbst nicht genau.
Für Details siehe ausführliche Beschreibung im "Fehlerhafte Datei / Screenshot Zuweisung" Thread.

Label: bug

**Comment by PeperoniRMA** [comment]
Hat sich erledigt. Lag an etwas anderem.

**Comment by rygos** [comment]
Woran, wenn ich fragen darf?

**Comment by PeperoniRMA** [comment]
Das hatten wir doch neulich besprochen ...
https://rmarchiv.tk/board/thread/6#c765
