### ISSUE TITLE
"maker_name" field for api/tako/filelist API endpoint

### ISSUE THREAD

**Issue by Ghabry** [RMArchiv/rmarchiv#267]
Would be useful to also have a maker_name field besides maker_id because when a new ID is added I have to manually update the download script to handle this (otherwise it puts the new games in the main folder :-1:)

**Comment by rygos** [comment]
Ok, its not easy to simply add this informations to the API output. But I have added a additional API endpoint.

For this you have to add the following to the config.php of the backup script:
`define('APIURLMAKER', 'https://rmarchiv.tk/api/tako/makers');`

you can Place this wherever you want in this file.

then you need to replace everything between
`$data = json_decode($json, true);` and `CliWriter::startProgress();`

with the following

```
$makerjson = file_get_contents(APIURLMAKER);
$makerjson = utf8_encode($makerjson);
$makerdata = json_decode($makerjson, true);

$maker = array();
// Get Maker Engines
foreach ($makerdata as $d){
    $maker[$d['id']] = $d['title'];
}

$i = 0;
```

**Comment by Ghabry** [comment]
That's good enough for me. thx!

**Comment by rygos** [comment]
You are welcome =)
