### ISSUE TITLE
Downloadzähler erhöht sich auch bei HEAD Request

### ISSUE THREAD

**Issue by Ghabry** [RMArchiv/rmarchiv#274]
``curl --head https://rmarchiv.tk/games/download/1018``

Ergebnis: Downloadzahl von diesem Spiel steigt um 1:

https://rmarchiv.tk/games/953

Nebenbei wäre es vllt. noch sinnvoll
"Disallow: /*/download/"
in die robots.txt einzutragen

**Comment by rygos** [comment]
Das der Counter hochgezählt wird, wenn man ein HEAD Request raus haut wurde behoben. 
Nun stellt sich die Frage, warum du das gemacht hast. Wolltest du damit die ankommende Dateigröße ermitteln?
Der Fix fragt im Prinzip nur ab ob es ein GET request ist oder nicht. Wenn nicht, dann passiert nichts.


Der 2. Punkt habe ich auch hinzugefügt. Danke dafür =)

**Comment by Ghabry** [comment]
ich ging davon aus, dass einige Crawler vllt. vorher HEAD machen, um zu schauen, ob das Besuchen Sinn macht und das verfälscht dann die Downloadzahl.
Denk mal die zwei Änderungen helfen gegen die Meisten Fake-Downloads. closing :)
