### ISSUE TITLE
randomgame.php off by 1

### ISSUE THREAD

**Issue by Ghabry** [RMArchiv/rmarchiv#275]
Denke mal Spiele mit Offset 0 gibts nicht (würde auch zeitgleich empfehlen zu prüfen, ob das letzte Spiel in der Liste durch den Zufall ausgewählt werden kann)

Herzlichen Glückwunsch. Du hast eine Seite gefunden, die einen internen Serverfehler verursacht hat.

Undefined offset: 0 (View: /var/www/vhosts/rmarchiv.tk/httpdocs/resources/views/index/_partials/randomgame.blade.php) (View: /var/www/vhosts/rmarchiv.tk/httpdocs/resources/views/index/_partials/randomgame.blade.php)

**Comment by rygos** [comment]
Ja, das entwickelt sich zu einem immer häufiger auftretenden Problem. Ich schaue es mir an!

**Comment by rygos** [comment]
Der ist seit dem nicht mehr bei mir aufgetreten.
